name = "VPEReg"
uuid = "47e5c925-5c02-4bfc-b219-526c43ce37a2"
repo = "https://github.com/VoxelPopuliEngine/VPEReg.git"
description = "Complementary Julia registry for VPE libraries to accelerate development"

[packages]
b4519675-ec9c-4dd5-a759-fbb42bea0e46 = { name = "GLFWAbstraction", path = "G/GLFWAbstraction" }
